/**
 * AUTH ERROR CODES
 * ============================================================
 * Debe reflejar EXACTAMENTE los códigos emitidos por el backend.
 */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED",
  INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN",
  EMAIL_ALREADY_CONFIRMED = "EMAIL_ALREADY_CONFIRMED",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  CONNECTION_ERROR = "CONNECTION_ERROR",
}
